/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import { useScrollbar } from '@14islands/r3f-scroll-rig'

export function Logo(props) {
  const { nodes } = useGLTF('/logo.glb')

  const vertex = 
  `
  void main(){
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
  `
  const fragment = 
`
void main(){
gl_FragColor = vec4(0.471,0.471,0.471, 1.0);
}

`
const logo = useRef()
const {__lenis} = useScrollbar()

useEffect(() => {
  if (!__lenis) return
  const onScroll = ({ progress, velocity }) => {
    const scale = (velocity * 0.3) + 100;
    logo.current.rotation.y = progress * Math.PI * 6;
    logo.current.scale.set(scale, scale, scale)
  }
  __lenis.on('scroll', onScroll)
  return () => __lenis.off('scroll', onScroll)
}, [__lenis])


  return (
    <group ref={logo} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bottom.geometry}
        material={nodes.Bottom.material}
        position={[0, 0.088, -0.001]}
      >
        <shaderMaterial vertexShader={vertex} fragmentShader={fragment} wireframe />
        </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Top.geometry}
        material={nodes.Top.material}
        position={[0, 1.129, -0.001]}
      >
        <shaderMaterial vertexShader={vertex} fragmentShader={fragment} wireframe />
        </mesh>
    </group>
  )
}

useGLTF.preload('/logo.glb')
